// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TokenMiner.Infrastructure.Persistence;

#nullable disable

namespace TokenMiner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002204850_AddPoolPayouts")]
    partial class AddPoolPayouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TokenMiner.Domain.Mining.Coin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer")
                        .HasColumnName("decimals");

                    b.Property<decimal?>("LastKnownUsdValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("last_known_usd_value");

                    b.Property<DateTimeOffset?>("LastValueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_value_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("network");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_coins");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coins_code");

                    b.ToTable("coins", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.CoinPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<decimal>("UsdValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("usd_value");

                    b.HasKey("Id")
                        .HasName("pk_coin_price_history");

                    b.HasIndex("CoinId", "ObservedAt")
                        .HasDatabaseName("ix_coin_price_history_coin_id_observed_at");

                    b.ToTable("coin_price_history", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.MiningAlgo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mining_algos");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_mining_algos_code");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_mining_algos_priority");

                    b.ToTable("mining_algos", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.MiningLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserHardwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_hardware_id");

                    b.Property<Guid>("UserHardwareMinerId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_hardware_miner_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mining_logs");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_mining_logs_coin_id");

                    b.HasIndex("PoolId")
                        .HasDatabaseName("ix_mining_logs_pool_id");

                    b.HasIndex("UserHardwareId")
                        .HasDatabaseName("ix_mining_logs_user_hardware_id");

                    b.HasIndex("UserHardwareMinerId")
                        .HasDatabaseName("ix_mining_logs_user_hardware_miner_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_mining_logs_user_id_created_at");

                    b.ToTable("mining_logs", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.MiningStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period");

                    b.Property<decimal>("UsdValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("usd_value");

                    b.Property<Guid>("UserHardwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_hardware_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mining_statistics");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_mining_statistics_coin_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mining_statistics_user_id");

                    b.HasIndex("UserHardwareId", "CoinId", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_mining_statistics_user_hardware_id_coin_id_period");

                    b.ToTable("mining_statistics", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("kryptex")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SystemPoolId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("system_pool_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pools");

                    b.HasIndex("SystemPoolId")
                        .IsUnique()
                        .HasDatabaseName("ix_pools_system_pool_id");

                    b.ToTable("pools", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.PoolCoin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.HasKey("Id")
                        .HasName("pk_pool_coins");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_pool_coins_coin_id");

                    b.HasIndex("PoolId", "CoinId")
                        .IsUnique()
                        .HasDatabaseName("ix_pool_coins_pool_id_coin_id");

                    b.ToTable("pool_coins", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.PoolDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("base_url");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayoutAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("payout_address");

                    b.Property<string>("PayoutMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payout_mode");

                    b.Property<string>("PayoutNetwork")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payout_network");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<string>("StatusEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("status_endpoint");

                    b.Property<string>("StratumEndpoint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("stratum_endpoint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pool_details");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_pool_details_coin_id");

                    b.HasIndex("PoolId")
                        .IsUnique()
                        .HasDatabaseName("ix_pool_details_pool_id");

                    b.ToTable("pool_details", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.UserHardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("hardware_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_hardware");

                    b.HasIndex("UserId", "HardwareId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_hardware_user_id_hardware_id");

                    b.ToTable("user_hardware", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.UserHardwareMiner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("MiningAlgoId")
                        .HasColumnType("uuid")
                        .HasColumnName("mining_algo_id");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pause_reason");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StopReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stop_reason");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<Guid>("UserHardwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_hardware_id");

                    b.Property<string>("WorkerIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_identifier");

                    b.HasKey("Id")
                        .HasName("pk_user_hardware_miners");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_user_hardware_miners_coin_id");

                    b.HasIndex("MiningAlgoId")
                        .HasDatabaseName("ix_user_hardware_miners_mining_algo_id");

                    b.HasIndex("PoolId")
                        .HasDatabaseName("ix_user_hardware_miners_pool_id");

                    b.HasIndex("UserHardwareId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_hardware_miners_user_hardware_id")
                        .HasFilter("status IN ('running', 'paused')");

                    b.HasIndex("WorkerIdentifier")
                        .HasDatabaseName("ix_user_hardware_miners_worker_identifier");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("ix_user_hardware_miners_status_last_activity_at");

                    b.ToTable("user_hardware_miners", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.UserMiningShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ApproxUsdValueAtTime")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("approx_usd_value_at_time");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<decimal?>("CoinValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("coin_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Difficulty")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Extranonce")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("extranonce");

                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_id");

                    b.Property<string>("Nonce")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nonce");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<string>("PoolResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("pool_response");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<string>("ResultHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("result_hash");

                    b.Property<string>("RewardStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reward_status");

                    b.Property<string>("ShareIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("share_identifier");

                    b.Property<DateTimeOffset>("ShareTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("share_timestamp");

                    b.Property<string>("Target")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target");

                    b.Property<Guid>("UserHardwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_hardware_id");

                    b.Property<Guid>("UserHardwareMinerId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_hardware_miner_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkerIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_identifier");

                    b.HasKey("Id")
                        .HasName("pk_user_mining_shares");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_user_mining_shares_coin_id");

                    b.HasIndex("UserHardwareId")
                        .HasDatabaseName("ix_user_mining_shares_user_hardware_id");

                    b.HasIndex("UserHardwareMinerId")
                        .HasDatabaseName("ix_user_mining_shares_user_hardware_miner_id");

                    b.HasIndex("PoolId", "ShareIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_user_mining_shares_pool_id_share_identifier");

                    b.HasIndex("RewardStatus", "CreatedAt")
                        .HasDatabaseName("ix_user_mining_shares_reward_status_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_user_mining_shares_user_id_created_at");

                    b.ToTable("user_mining_shares", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Treasury.PoolPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CoinId")
                        .HasColumnType("uuid")
                        .HasColumnName("coin_id");

                    b.Property<int>("ConfirmationsCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmations_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<decimal>("RedeemedAmount")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("redeemed_amount");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("transaction_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id")
                        .HasName("pk_pool_payouts");

                    b.HasIndex("CoinId")
                        .HasDatabaseName("ix_pool_payouts_coin_id");

                    b.HasIndex("PoolId", "TransactionHash")
                        .IsUnique()
                        .HasDatabaseName("ix_pool_payouts_pool_id_transaction_hash");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_pool_payouts_status_updated_at");

                    b.ToTable("pool_payouts", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_normalized");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_login_attempts");

                    b.HasIndex("EmailNormalized", "CreatedAt")
                        .HasDatabaseName("ix_login_attempts_email_normalized_created_at");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.HasIndex("UserId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_otp_codes_user_id_purpose_created_at");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<string>("GoogleSub")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_sub");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_sub");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Infrastructure.Persistence.ServiceRequestNonce", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_id");

                    b.Property<string>("Nonce")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nonce");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("ServiceId", "Nonce")
                        .HasName("pk_service_request_nonces");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_service_request_nonces_expires_at");

                    b.ToTable("service_request_nonces", (string)null);
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.CoinPriceHistory", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coin_price_history_coins_coin_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.MiningLog", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mining_logs_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mining_logs_pools_pool_id");

                    b.HasOne("TokenMiner.Domain.Mining.UserHardware", null)
                        .WithMany()
                        .HasForeignKey("UserHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mining_logs_user_hardware_user_hardware_id");

                    b.HasOne("TokenMiner.Domain.Mining.UserHardwareMiner", null)
                        .WithMany()
                        .HasForeignKey("UserHardwareMinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mining_logs_user_hardware_miners_user_hardware_miner_id");

                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mining_logs_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.MiningStatistic", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mining_statistics_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.UserHardware", null)
                        .WithMany()
                        .HasForeignKey("UserHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mining_statistics_user_hardware_user_hardware_id");

                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mining_statistics_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.PoolCoin", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pool_coins_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pool_coins_pools_pool_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.PoolDetails", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pool_details_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pool_details_pools_pool_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.UserHardware", b =>
                {
                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_hardware_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.UserHardwareMiner", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_hardware_miners_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.MiningAlgo", null)
                        .WithMany()
                        .HasForeignKey("MiningAlgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_hardware_miners_mining_algos_mining_algo_id");

                    b.HasOne("TokenMiner.Domain.Mining.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_hardware_miners_pools_pool_id");

                    b.HasOne("TokenMiner.Domain.Mining.UserHardware", null)
                        .WithMany()
                        .HasForeignKey("UserHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_hardware_miners_user_hardware_user_hardware_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Mining.UserMiningShare", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_mining_shares_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_mining_shares_pools_pool_id");

                    b.HasOne("TokenMiner.Domain.Mining.UserHardware", null)
                        .WithMany()
                        .HasForeignKey("UserHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mining_shares_user_hardware_user_hardware_id");

                    b.HasOne("TokenMiner.Domain.Mining.UserHardwareMiner", null)
                        .WithMany()
                        .HasForeignKey("UserHardwareMinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mining_shares_user_hardware_miners_user_hardware_miner");

                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mining_shares_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Treasury.PoolPayout", b =>
                {
                    b.HasOne("TokenMiner.Domain.Mining.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pool_payouts_coins_coin_id");

                    b.HasOne("TokenMiner.Domain.Mining.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pool_payouts_pools_pool_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.EmailVerificationToken", b =>
                {
                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.OtpCode", b =>
                {
                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otp_codes_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("TokenMiner.Domain.Users.UserRole", b =>
                {
                    b.HasOne("TokenMiner.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("TokenMiner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
