<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>TokenMiner.Api</RootNamespace>
    <AssemblyName>TokenMiner.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TokenMiner.Application\TokenMiner.Application.csproj" />
    <ProjectReference Include="..\TokenMiner.Contracts\TokenMiner.Contracts.csproj" />
    <ProjectReference Include="..\TokenMiner.Infrastructure\TokenMiner.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>
