//! The vendored stack's own known-answer vectors, embedded so the port can be
//! checked without the submodule present at test time.
//!
//! [`TINY`] is from [`minerReference.test.js`](vendor/llmjob/earn/test/minerReference.test.js),
//! generated by llmjob's JavaScript reference (`reference.js`), which is itself built on a BLAKE3
//! checked against the published vectors. This is the set a CPU test can pass: it exercises
//! `config52`, `job_key`, the salted root binding, the seed chain and the transcript fold in pure
//! arithmetic.
//!
//! Why the vectors matter more than usual here: every failure this miner can have is silent. A
//! wrong `config52` byte, a keyed where an unkeyed hash belonged, a swapped seed, a fold that
//! resets its accumulator per chunk — each runs at full speed, reports a healthy hashrate and
//! simply never earns. A frozen intermediate turns "wrong" into "wrong *here*".
//!
//! **What is deliberately absent.** llmjob also ships
//! [`minerDeviceParity.test.js`](vendor/llmjob/earn/test/minerDeviceParity.test.js): jackpot
//! hashes captured from a real CUDA core on an RTX 4090. They cannot be embedded here, because
//! they were captured at `k = 512, rank = 32` and `pearl_host_submit` refuses any k/rank but the
//! mandated `2048/128` — the core would not run the geometry they describe, so replaying them
//! through it is not merely slow, it is impossible. (That refusal is `pearl_host.cu`'s own, not a
//! limitation of this port; llmjob's JS tests can still use them, because they never load the
//! `.node`.) The on-device half of the gate is therefore a live self-test at a real profile, in
//! [`super::engine`], rather than a replay of frozen bytes.

use super::config::{
    build_config52, job_key, Profile, COLS_PATTERN, ROWS_PATTERN,
};

/// The reference's tiny profile: `k/rank = 16` (one chunk per transcript lane, so the rotation
/// never wraps), the real 16x16 strided tile, and `m`/`n` small enough to fold on the CPU.
pub const TINY: Profile = Profile {
    k: 512,
    rank: 32,
    mma_type: 0,
    m: 128,
    n: 128,
    seed_derivation: super::config::SEED_SALTED,
    col_batch: 2048,
    hash_big_endian: 0,
    operand_fill: super::config::OPERAND_CONST,
    rows: ROWS_PATTERN,
    cols: COLS_PATTERN,
};

/// `header76` from the reference tests: byte for byte, `h[i] = i` for every `i in 0..76`.
pub fn header76() -> [u8; 76] {
    let mut h = [0u8; 76];
    for (i, byte) in h.iter_mut().enumerate() {
        *byte = i as u8;
    }
    h
}

/// A header of seventy-six `0x01` bytes: the one llmjob's device-parity vectors
/// were captured under, and what the engine's live self-test mines against.
///
/// `const` so it can initialise constants and needs no runtime setup before the
/// startup gate reaches it.
pub const fn header_all_ones() -> [u8; 76] {
    [0x01u8; 76]
}

/// Known-answer vectors for the pure-PearlHash path, frozen by the reference implementation.
///
/// Only `job_key` is read at runtime — the startup gate pins the ported
/// `config52` against it. The rest are the reference's downstream values, kept
/// whole so the vectors read as the reference's own record and so the hex
/// decoder has more than one digest to prove itself on; a test reads them all.
#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub struct ReferenceVector {
    pub name: &'static str,
    /// `blake3(header76 ‖ config52)`, unkeyed.
    pub job_key: [u8; 32],
    /// `blake3(pad1024(A_rowmajor), key=job_key)` — the raw A root, before cert-v3 binding.
    pub hash_a: [u8; 32],
    /// `blake3(pad1024(Bᵀ), key=job_key)` — the raw B root, before cert-v3 binding.
    pub hash_b: [u8; 32],
    /// `blake3(job_key ‖ bound_b)`; derived first and feeding `a_seed`.
    pub b_seed: [u8; 32],
    /// `blake3(b_seed ‖ bound_a)`; keys the transcript.
    pub a_seed: [u8; 32],
    /// `blake3(transcript64, key=a_seed)` — the value a pool compares against its target.
    pub jackpot_hash: [u8; 32],
}

const fn hex32(s: &str) -> [u8; 32] {
    let bytes = s.as_bytes();
    assert!(bytes.len() == 64, "a digest is 64 hex characters");
    let mut out = [0u8; 32];
    let mut i = 0;
    while i < 32 {
        out[i] = (hex_nibble(bytes[2 * i]) << 4) | hex_nibble(bytes[2 * i + 1]);
        i += 1;
    }
    out
}

const fn hex_nibble(c: u8) -> u8 {
    match c {
        b'0'..=b'9' => c - b'0',
        b'a'..=b'f' => c - b'a' + 10,
        b'A'..=b'F' => c - b'A' + 10,
        _ => panic!("not a hex digit"),
    }
}

/// The TINY reference vector. Every value reproduced by llmjob's `reference.js` from `TINY` and
/// the two synthetic operands `A[i] = (i*7 % 127) - 63`, `Bt[i] = (i*13 % 127) - 63`.
pub const TINY_VECTOR: ReferenceVector = ReferenceVector {
    name: "minerReference.test.js TINY",
    job_key: hex32("5a33dfe9636c60b135a0ff4b32ac8d510ea5c2b62eef2e781739df8fb3682cf9"),
    hash_a: hex32("2840a6169276a672e0daa23c687ad3958d5d7eb5082c4b87556d768c6de90251"),
    hash_b: hex32("4c44eab12bf6ab823b2111835456a2fd76c40e2f76f218e87acf90e1456d29a5"),
    b_seed: hex32("6f8658385babc297c5fbccea48d62b86661edc24ceff2c89c932438522b780c8"),
    a_seed: hex32("ac53440df442db0937eecd0e672669ef137347a4c17dcbbb7cea2e575373e7fa"),
    jackpot_hash: hex32("53297db801b9dbece5537534573faf28e21e17496812ebf4ad69e1caa2c1ba90"),
};

/// The reference's synthetic int7 operand `A`: `A[i] = (i*7 % 127) - 63`.
#[cfg(test)]
pub fn reference_operand_a(len: usize) -> Vec<i8> {
    (0..len).map(|i| ((i * 7) % 127) as i8 - 63).collect()
}

/// The reference's synthetic int7 operand `Bt`: `Bt[i] = (i*13 % 127) - 63`.
#[cfg(test)]
pub fn reference_operand_b(len: usize) -> Vec<i8> {
    (0..len).map(|i| ((i * 13) % 127) as i8 - 63).collect()
}

/// `job_key` for the reference's TINY profile and header, straight from the ported maths.
pub fn tiny_job_key() -> [u8; 32] {
    job_key(&header76(), &build_config52(&TINY))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The vectors decode to the bytes the JS produced. This is the one check that the
    /// hand-rolled `const fn` hex decoder is right; without it a decoder that dropped a nibble
    /// would make every vector below fail for a reason that has nothing to do with the port.
    #[test]
    fn the_vectors_decode_to_the_published_digests() {
        assert_eq!(
            TINY_VECTOR.job_key[0], 0x5a,
            "the first byte of the TINY jobKey"
        );
        assert_eq!(TINY_VECTOR.a_seed[31], 0xfa);
        assert_eq!(TINY_VECTOR.b_seed[31], 0xc8);
        assert_eq!(TINY_VECTOR.jackpot_hash[31], 0x90);
    }

    /// The TINY `job_key` is `blake3(header76 ‖ config52)` and nothing else. If the ported
    /// `config52` layout or the unkeyed hash is wrong, this is where it shows — and it is the
    /// first thing every downstream value depends on.
    #[test]
    fn the_tiny_job_key_matches_the_reference() {
        assert_eq!(
            tiny_job_key(),
            TINY_VECTOR.job_key,
            "config52 or the unkeyed job_key hash does not match reference.js"
        );
    }

    /// The reference's operands are the shape the vectors were built for: int7, and defined
    /// arithmetically so a test can regenerate them without a fixture file.
    #[test]
    fn the_reference_operands_are_in_int7_range() {
        let a = reference_operand_a(16);
        assert_eq!(a[0], -63);
        assert_eq!(a[1], -56);
        let b = reference_operand_b(16);
        assert_eq!(b[0], -63);
        assert!(a.iter().all(|&v| (-63..=63).contains(&v)));
        assert!(b.iter().all(|&v| (-63..=63).contains(&v)));
    }
}
